server.port=8081
spring.application.name=patient-service
spring.config.import=optional:configserver:http://localhost:8888

# Mở endpoint Actuator bao gồm /actuator/refresh
management.endpoints.web.exposure.include=*

# Eureka client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false